### ISSUE TITLE
manage_logind parameter does not work in 0.1.47.

### ISSUE THREAD

**Issue by nvergottini** [NTTCom-MS/eyp-systemd#113]
I see that there is a class parameter to not manage logind.conf. but it does not currently work in 0.1.47. I see there is a tag 0.1.48 in GitHub that will fix it. Any chance Puppet Forge will be updated soon to 0.1.48?

**Comment by davidnewhall** [comment]
This was merged, but I cannot comment on when it will be "released."
https://github.com/NTTCom-MS/eyp-systemd/pull/106

**Comment by davidnewhall** [comment]
I think a large portion of https://github.com/NTTCom-MS/eyp-systemd/pull/84 was accidentally reverted in a rebase or merge squash here: https://github.com/NTTCom-MS/eyp-systemd/pull/87/commits/d8645786b8df04de7d20cf67b7674744643a0ab6

**Comment by jordiprats** [comment]
Hi,
This option have been reworked in the 0.2 branch.

This option no longer exists, if you want to manage logind option you must include the systemd::logind class

kind regards,
