### ISSUE TITLE
Support for BindsTo option

### ISSUE THREAD

**Issue by rassaei** [NTTCom-MS/eyp-systemd#118]
I noticed there is no support for the "BindsTo=" option in the [Unit] section (as specified here https://www.freedesktop.org/software/systemd/man/systemd.unit.html#BindsTo=)
Can you consider adding it?

**Comment by jordiprats** [comment]
Hi,
I've added this option on the [0.2.5](https://github.com/NTTCom-MS/eyp-systemd/releases/tag/0.2.5) release

kind regards,
