### ISSUE TITLE
failures when defining a target

### ISSUE THREAD

**Issue by ArVincentr** [NTTCom-MS/eyp-systemd#128]
Hi,

I was doing some tests this morning on a system when I  got this issue.

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template systemd/section/unit.erb:
  Filepath: /etc/puppetlabs/code/environments/xxx/modules/systemd/templates/section/unit.erb
  Line: 11
  Detail: undefined method `any?' for nil:NilClass`

the issue was caused by variables used in the template not being defined at target.pp.

I have worked this out and could fix it in my own fork (will propose and PR) I hope this helps

**Comment by jordiprats** [comment]
Hi,
As I said in your [PR-129](https://github.com/NTTCom-MS/eyp-systemd/pull/129), this issue have been solved on [0.2.1](https://github.com/NTTCom-MS/eyp-systemd/releases/tag/0.2.1)

kind regards,
