### ISSUE TITLE
Restrictive file permissions in module breaks r10k workflow

### ISSUE THREAD

**Issue by smoeding** [NTTCom-MS/eyp-systemd#132]
We use `r10k` to deploy modules using a different user id (not `puppet`). Unfortunately the module currently has a couple of files missing read permission for _others_. These files are therefore unreadable for the Puppetmaster process running as user `puppet`.

**Comment by jordiprats** [comment]
Hi,
Thanks for reporting, could you please clarify which files have file modes that you feel are too restrictive?

kind regards,

**Comment by ArVincentr** [comment]
Hi,

Not 100% sure we are speaking about the same but from the tests I did, I could spot the following issue.

~/metadata.json
~/manifests/service.pp
~/manifests/target.pp
~/templates/section/* 

are having wrong permission permission... I think 640 instead of 644 ( but needs to confirm as I fixed them manually )

Regards

**Comment by jordiprats** [comment]
Hi,
I'm not really sure how this could happen, I'm actually using r10k for deployments without issues so I'm not sure how you are use r10k that triggers this issue.

On the other hand, AFAIK git only keeps track of the x bit, not the full filemode:

```
jprats@croscat:~/git/NTTCom-MS/eyp-systemd$ ls -la README.md 
-rw-rw---- 1 jprats jprats 22802 may 20 16:30 README.md
jprats@croscat:~/git/NTTCom-MS/eyp-systemd$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
jprats@croscat:~/git/NTTCom-MS/eyp-systemd$ chmod o+r README.md 
jprats@croscat:~/git/NTTCom-MS/eyp-systemd$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
jprats@croscat:~/git/NTTCom-MS/eyp-systemd$ git diff
jprats@croscat:~/git/NTTCom-MS/eyp-systemd$ 
```

kind regards,

**Comment by smoeding** [comment]
It's not an issue with git but with the packaging. The (now deleted) modules that I downloaded from forge.puppet.com were missing the `r` bit for `others`.

In my setup I use different users on the Puppetmaster: `puppet` for running the Puppetmaster and `r10k` for running r10k to do the deployments. When `r10k` deploy modules from the Forge the missing `other` permissions will render the files unreadable for the `puppet` user.

Release 0.2.4 seems to look better. Thanks!

**Comment by smoeding** [comment]
Sorry, too quick. `manifests/service/dropin.pp` still has too tight permissions for my environment...

**Comment by jordiprats** [comment]
Hi,
Ok, I was misunderstanding the problem, thanks for clarifying!

It will be fixed once I push some changes I have pending.

thanks,

**Comment by jordiprats** [comment]
Hi,
I've uploaded a new release [0.2.5](https://github.com/NTTCom-MS/eyp-systemd/releases/tag/0.2.5) with all files with o+r

Regarding r10k I would suggest to use git tags instead of relying on puppet forge as follows:

```
mod 'eyp-systemd',
   :git => 'https://github.com/NTTCom-MS/eyp-systemd.git',
   :tag => '0.2.5'
```

Could you please check if the issue with the puppet forge build is fixed?

kind regards,

**Comment by ArVincentr** [comment]
Right,

I am not at the office anymore but this is first thing I will do. We are also using r10k so I'll give my feedback as well 

Regards
Vincent

**Comment by smoeding** [comment]
Version 0.2.5 works for me. Thanks!

I've used tagged access to git for our local modules in a local Gitlab as I don't want to package them. I will think about your suggestion for public modules. But I am a bit concerned about unwanted changes if someone moves an existing tag to a new commit. I don't think I can prevent that...

Regards!
