### ISSUE TITLE
Wrong permission

### ISSUE THREAD

**Issue by dominiquearpin** [NTTCom-MS/eyp-systemd#143]
I need to ajust file permission on metadata.json to add read access to other.  

Error:
Could not evaluate: Could not retrieve file metadata for puppet:///pluginfacts: Error 500 on SERVER: Server Error: Permission denied - /etc/puppetlabs/code/environments/production/modules/systemd/metadata.json

**Comment by jordiprats** [comment]
Hi,
I've uploaded version 0.2.8 to the forge with o+r

kind regards,
