### ISSUE TITLE
Allow UnsetEnvironment

### ISSUE THREAD

**Issue by devinmatte** [NTTCom-MS/eyp-systemd#152]
I need to create a dropin that unsets an Environment variable. There should be a way to do that through here similar to `env_vars`

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment

**Comment by jordiprats** [comment]
Hi,
I've added support to UnsetEnvironment on [PR-160](https://github.com/NTTCom-MS/eyp-systemd/pull/160) version 0.1.12

kind regards,
