### ISSUE TITLE
Allow to not supply "wantedby"

### ISSUE THREAD

**Issue by TuningYourCode** [NTTCom-MS/eyp-systemd#161]
Currently it is not possible to omit the "wantedby" attribute because if you give `undef` puppet will use the default value `[ 'multi-user.target' ]`.
Empty array also results in an config entry in the config file as the template checks for defined.

We want to do this as it is required to not trigger systemd timers on reboot or creation of new timers (they will run on first puppet run after creation or if you stop the .timer and puppet reenables them)

https://unix.stackexchange.com/questions/363976/prevent-systemd-timer-from-running-on-startup/389737#389737

**Comment by jordiprats** [comment]
Hi,
I've merged your PR using [PR-164](https://github.com/NTTCom-MS/eyp-systemd/pull/164)

kind regards,
