### ISSUE TITLE
Remove is_array usage

### ISSUE THREAD

**Issue by htj** [NTTCom-MS/eyp-systemd#174]
Hi

We get this warning when using service:

Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Array instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["/var/cache/cosmos/model/modules/systemd/manifests/service.pp", 80]:
   (location: /var/cache/cosmos/model/modules/stdlib/lib/puppet/functions/deprecation.rb:34:in `deprecation')

This might is somewhat related to #61 
I know it is mostly cosmetic.

**Comment by jordiprats** [comment]
I have a [preliminary version](https://github.com/jordiprats/eyp-systemd). Do you want to test it and provide some feedback?

**Comment by htj** [comment]
Hi

Thanks. I'll try and take a look at it within the next couple of working days.

**Comment by jordiprats** [comment]
Hi,
This have been already merged, I'm closing this issue

kind regards,
