### ISSUE TITLE
Feature: add support for unit file override 

### ISSUE THREAD

**Issue by cedef** [NTTCom-MS/eyp-systemd#49]
As specified by the [systemd.unit manual](https://www.freedesktop.org/software/systemd/man/systemd.unit.html) it is possible to override vendor settings by creating a `unit.d` directory containing one or multiple `foobar.conf` config files that override only a specific setting.

I would be glad to implement this feature but I would like your opinion on how to do it.

I think I would update `systemd::service` defined type in order to:

- add a `$unit_d_override` boolean parameter (that defaults to `false`)
- add a `$unit_d_purge` boolean param (defaults to `true`)
- modify `service.erb` template to make every section/directive optional (i.e. `WantedBy`, `User`...) so that we can drop a file containing only relevant section(s) and directive(s).

When `$unit_d_override = true`, systemd::service would automatically create the `/etc/systemd/system/example.service.d/50-override.conf` file with provided directives in it.
If `$unit_d_purge = true` then the directory would have `purge => true`.

What do you think about that ?

Regards,

**Comment by cedef** [comment]
Any news about that one ?

**Comment by davidnewhall** [comment]
I'm not a maintainer or allowed-contributor to this code base, but my opinion, for what it's worth is:

You should create a new defined type for overrides. This way you can call one type with the original unit file and another type with the override. This becomes handy when you have two modules that need to update the same service.

**Comment by jduemes** [comment]
@cedef - Are you talking about drop-in files ?

**Comment by cedef** [comment]
@jduemes : I'm currently on holidays. Should do it by mid-september.
If you would like to start the job, please do :)

**Comment by juliantaylor** [comment]
a PR adding the feature has appeared: https://github.com/NTTCom-MS/eyp-systemd/issues/49

**Comment by jordiprats** [comment]
Hi,
I've merged [PR-57](https://github.com/NTTCom-MS/eyp-systemd/pull/57) in version **0.35** and added some features requested here that will be merged shortly into **0.1.37** (today or tomorrow)

regards,
Jordi
