### ISSUE TITLE
Confusing `exec`.

### ISSUE THREAD

**Issue by davidnewhall** [NTTCom-MS/eyp-systemd#54]
As a matter of continuity and to avoid confusion or conflicts, can you consider renaming this `exec` https://github.com/NTTCom-MS/eyp-systemd/blob/72a06f26bcfa1f60a72fa6cdb1b8c1b246208abd/manifests/init.pp#L10 to `'systemctl daemon-reload'`? This request is because `systemctl reload` is a valid command and it may appear in other modules as an `exec` title.

**Comment by jordiprats** [comment]
Hi,
I've renamed this exec in **0.1.36**

Thanks for pointing this out

regards,
