### ISSUE TITLE
oneshot jobs produce invalid service without explicit restart  => no

### ISSUE THREAD

**Issue by juliantaylor** [NTTCom-MS/eyp-systemd#55]
When adding oneshot service just defining description, execstart and type = oneshot the module produces a file with the Restart set to the default always.
systemd rejects this:

    Service has Restart= setting other than no, which isn't allowed for Type=oneshot services

It would be nice when the restart is implicitly removed or set to no from the generated service description for oneshot type services.

**Comment by jordiprats** [comment]
Hi,
Although this can be easily avoided setting restart to 'no' I think setting restart to 'always' by default can cause unexpected conflicts like this one.

This is going to be fixed in 0.1.36 by setting restart default value to undef

Thanks for reporting this issue

best regards,

**Comment by jordiprats** [comment]
Commit that changed default value for restart is [f83f3b9c13fc1a17087bd8243e7880679486d19a](https://github.com/NTTCom-MS/eyp-systemd/commit/f83f3b9c13fc1a17087bd8243e7880679486d19a)

**Comment by juliantaylor** [comment]
I don't think this is a good enough reason to change a default.
I would prefer it when it instead just errors out or defaults to no only if oneshot is set.
