### ISSUE TITLE
0.1.34 missing function_bool2yesno

### ISSUE THREAD

**Issue by FayeG** [NTTCom-MS/eyp-systemd#56]
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Failed to parse template systemd/service.erb:
  Filepath: org/jruby/RubyBasicObject.java
  Line: 1555
  Detail: undefined method `function_bool2yesno' for Scope(Systemd::Service[lsf]):Puppet::Parser::Scope
 at /etc/puppetlabs/code/environments/international_aws_test/modules/systemd/manifests/service.pp:96:16 at ....

**Comment by cedef** [comment]
@FayeG how did you install the eyp-systemd module ? Looks like the module eyp-eyplib (a [direct eyp-systemd module dependency](https://forge.puppet.com/eyp/systemd/dependencies)) is missing.

**Comment by FayeG** [comment]
Ah that would do it. Thanks.
