### ISSUE TITLE
one more step to Puppet 4 : replace `validate_*` with data types ?

### ISSUE THREAD

**Issue by cedef** [NTTCom-MS/eyp-systemd#61]
I wonder if you would be OK to introduce [Puppet 4 data types](https://docs.puppet.com/puppet/4.10/lang_data_type.html) for data type validation.
I'm thinking especially about the **deprecated** `validate_*`functions which could be replaced by data types when submitting PR.

Regards,

**Comment by jtreminio** [comment]
Fixed by https://github.com/NTTCom-MS/eyp-systemd/pull/77

**Comment by jordiprats** [comment]
As this will break compatibility with puppet 3.8 I'm going to merge [PR-77](https://github.com/NTTCom-MS/eyp-systemd/pull/77) in eyp-systemd version **0.2.0**

best regards,

**Comment by jordiprats** [comment]
Hi,
This issue have been fixed on the version 0.3.0

kind regards,
