### ISSUE TITLE
Default values for parameters : should be identical to systemd defaults

### ISSUE THREAD

**Issue by cedef** [NTTCom-MS/eyp-systemd#62]
I've noticed that some default values differs between the module code and systemd's.
Examples:

- `systemd::service` class has `$restart = 'always'` while systemd.service manual says it defaults to `no`.
- `systemd` class has `$remove_ipc='no'` while logind.conf manual says it defaults to `yes`

In my opinion, it's **crucial** to stick to 1) Distributions values, 2) _upstream_ values via hiera in module or params.pp paradigms if they differs.

We can stille use hiera to override company's default values.

**Comment by jordiprats** [comment]
Hi,
In the 0.2 branch I've modified some default values to make it safer. Anyway, I don't want to introduce too many drastic changes. I believe we should not be sticking to defaults that make no sense thus only defaults that make sense to change it will be changed

kind regards,
