### ISSUE TITLE
Missing Release Tags in Repository

### ISSUE THREAD

**Issue by johnzimm** [NTTCom-MS/eyp-systemd#64]
Referencing the forge: https://forge.puppet.com/eyp/systemd

Current release is '0.1.34', but there is no tag in the git repo.

When managing a Puppetfile and using git sources the tag is extremely useful rather than using a commit hash as the ref.

**Comment by jordiprats** [comment]
Hi,
I've created the following docker image to be able to automate tag generation: [docker-eyptagger
](https://github.com/NTTCom-MS/docker-eyptagger)

I'm going to keep this issue open for some releases to check it is working fine

best regards,

**Comment by jordiprats** [comment]
Tag creation is now automated, at every version change is going to be updated

I'm closing this issues

regards,
