### ISSUE TITLE
new forge release?

### ISSUE THREAD

**Issue by juliantaylor** [NTTCom-MS/eyp-systemd#83]
hi,
can you create a new puppet forge release?
It is still on version 0.1.35 which for example does not yet support debian 9 (stretch)

**Comment by jordiprats** [comment]
Hi,
I've manually uploaded the latest version: **0.1.41** but as long as I cannot see any way (other than travis which I don't like) to automate releases this is still a manual process. I would suggest to use Puppetfiles with tags:

https://docs.puppet.com/pe/3.8/r10k_puppetfile.html

```
mod 'systemd',
  :git => 'https://github.com/NTTCom-MS/eyp-systemd.git',
  :tag => '0.1.41'
```

Please bear in mind that applying this using r10k will delete any other puppet module that is not included in the Puppetfile and it will not install dependencies

I have a script that uses r10k to install puppet modules from git repositories that I'm using for testing and module development: [puppetmasterless](https://github.com/jordiprats/puppet-masterless)



regards,
