### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by gbjtv** [NTTCom-MS/eyp-systemd#90]
https://github.com/NTTCom-MS/eyp-systemd/blob/cf0aab86f34887b1861806c5ae286804601c57da/manifests/params.pp#L23

Possible to add support for ubuntu 18.04 support?

**Comment by jordiprats** [comment]
Hi,
I've added support for Ubuntu 18.04 in version [0.1.43](https://github.com/NTTCom-MS/eyp-systemd/blob/master/CHANGELOG.md)

best regards,
