### ISSUE TITLE
The module should work with Fedora

### ISSUE THREAD

**Issue by jcbollinger** [NTTCom-MS/eyp-systemd#99]
Fedora is of course a RedHat-family Linux, and it has relied on systemd for longer than RHEL has done, but the module expressly rejects Fedora clients:

> Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Function Call, Unsupported RHEL/CentOS version! (file: [/path/to]/modules/systemd/manifests/params.pp, line: 12, column: 20)

The error message itself appears to arise because Fedora uses different version numbering than does RHEL.

Fedora is not presently documented among the supported distros, so I guess this is a feature request, not a bug report.

**Comment by jordiprats** [comment]
Hi,
I've blindly added support for OpenSuSE and Fedora, could you please check if it is working for you?

Right now [0.1.47](https://github.com/NTTCom-MS/eyp-systemd/releases/tag/0.1.47) is set as a pre-release

best regards,

**Comment by jordiprats** [comment]
I'm setting this issue as resolved, I've also changed the 0.1.47 status to release

best regards,
